version: "3"

services:
  proxy:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./custom.conf:/etc/nginx/conf.d/custom.conf
      - ./data/html:/usr/share/nginx/html
      - ./data/vhost.d:/etc/nginx/vhost.d
      - ./data/certs:/etc/nginx/certs:ro
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
networks:
  default:
    external:
      name: nginx-proxy